version: '3.8'
services:
  chat-service:
    build: ./chat-service
    ports:
      - "8085:8085"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - kafka
      - postgres

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - chat-service
      - history-service
      - recommendation-service
      - subscription-service
      - user-service

  history-service:
    build: ./history-service
    ports:
      - "8084:8084"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/yourdatabase
    depends_on:
      - postgres
      - kafka

  recommendation-service:
    build: ./recommendation-service
    ports:
      - "8083:8083"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/yourdatabase
    depends_on:
      - mysql
      - kafka

  subscription-service:
    build: ./subscription-service
    ports:
      - "8082:8082"
    environment:
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/yourdatabase
    depends_on:
      - mysql
      - kafka

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/yourdatabase
    depends_on:
      - mysql
      - kafka

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: yourdatabase
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: yourdatabase
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
